### PR TITLE
Add TensorFlow examples - ResNet50 and BERT models

### PR DESCRIPTION
**Pull request by Satya1493**
Signed-off-by: Satyanaraya Illa <satyanaraya.illa@intel.com>

## Description of the changes 
TensorFlow examples for ResNet50 and BERT models. The samples run inference using pre-trained models.

## How to test this PR? 
Please follow steps present at tensorflow/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/7)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/7)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @Satya1493)

___
*[tensorflow/README.md, line 54 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnJwAiAFHbc1oqk3qf:-MqnJwAjEStzJE4xf8ws:b5yp7df) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/README.md#L54)):*
> ```Markdown
> - To run int8 inference on ``gramine-direct`` (non-SGX version), replace ``gramine-sgx`` with
> ``gramine-direct`` in the above command.
> - To run int8 inference on native baremetal (outside Gramine), replace ``gramine-sgx ./python`` with
> ```

`on native baremetal (outside Gramine)` -> `natively (outside Gramine)`
___
*[tensorflow/README.md, line 71 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnJzYF4PF8KGgGpEFW:-MqnJzYG7bdQCWJBRk3_:b5yp7df) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/README.md#L71)):*
> ```Markdown
> - To run inference on ``gramine-direct`` (non-SGX version), replace ``gramine-sgx`` with
> ``gramine-direct`` in the above command.
> - To run inference on native baremetal (outside Gramine), replace ``gramine-sgx ./python`` with
> ```

`on native baremetal (outside Gramine)` -> `natively (outside Gramine)`
___
*[tensorflow/README.md, line 89 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnKPaS1Fi3UsRR1k-S:-MqnKPaS1Fi3UsRR1k-T:bply65e) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/README.md#L89)):*
> ```Markdown
> - To get the number of cores per socket, do ``lscpu | grep 'Core(s) per socket'``.
> 
> ## Performance considerations
> ```

Could you copy-paste this section from https://github.com/gramineproject/examples/pull/6/files? I already reviewed the OpenVINO PR, and all comments pertaining to this `Performance considerations` section were already resolved in that OpenVINO PR.

It looks to me that these sections are 95% identical, except for `libos.check_invalid_pointers` manifest option. Don't you want to add the description of this option in your README?
___
*[tensorflow/BERT/Makefile, line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLaCY-XKGSo7y6cGR:-MqnLaCZ3Q3yUVTtXCDf:b-x45em2) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/Makefile#L1)):*
> ```Makefile
> # BERT sample for Tensorflow
> ```

`Tensorflow` -> `TensorFlow`
___
*[tensorflow/BERT/python.manifest.template, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLADPDMV_JP-surWE:-MqnLADPDMV_JP-surWF:b-73j6cz) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/python.manifest.template#L2)):*
> ```
> libos.entrypoint = "{{ entrypoint }}"
> loader.preload = "file:{{ gramine.libos }}"
> ```

Latest Gramine uses `loader.entrypoint` instead of `loader.preload`. Please see this commit: https://github.com/gramineproject/examples/commit/ebc051be9dad032da789a27387c36db3cbadbc95
___
*[tensorflow/BERT/python.manifest.template, line 8 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnMV881u9MRm00RuQ5:-MqnMV881u9MRm00RuQ6:b4p4q49) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/python.manifest.template#L8)):*
> ```
> loader.insecure__use_cmdline_argv = true
> loader.insecure__use_host_env = true
> loader.insecure__disable_aslr = true
> ```

OpenVINO PR (https://github.com/gramineproject/examples/pull/6) also has `libos.check_invalid_pointers = false`. Do you want to add this option here, for performance? Or does it break TensorFlow?
___
*[tensorflow/BERT/python.manifest.template, line 55 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLuk14tUzQB2zlPVw:-MqnLuk14tUzQB2zlPVx:bms62ve) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/python.manifest.template#L55)):*
> ```
>   "file:{{ arch_libdir }}/",
>   "file:/usr/{{ arch_libdir }}/",
>   "file:{{ entrypoint }}/",
> ```

You have a `/` at the end here, this can't be right -- the `{{ entrypoint }}` is a file, not a directory. Please remove the trailing `/`.
___
*[tensorflow/ResNet50/Makefile, line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLddLAfKLjMxVRppk:-MqnLddLAfKLjMxVRppl:b-x45em2) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/Makefile#L1)):*
> ```Makefile
> # ResNet50 sample for Tensorflow
> ```

`Tensorflow` -> `TensorFlow`
___
*[tensorflow/ResNet50/python.manifest.template, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLILV-D2DIGVWQ-_q:-MqnLILW0-aO0M6Ux0X1:b-73j6cz) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L2)):*
> ```
> libos.entrypoint = "{{ entrypoint }}"
> loader.preload = "file:{{ gramine.libos }}"
> ```

Latest Gramine uses `loader.entrypoint` instead of `loader.preload`. Please see this commit: https://github.com/gramineproject/examples/commit/ebc051be9dad032da789a27387c36db3cbadbc95
___
*[tensorflow/ResNet50/python.manifest.template, line 8 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnMda44Ursgyn4LEF1:-MqnMda44Ursgyn4LEF2:b4p4q49) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L8)):*
> ```
> loader.insecure__use_cmdline_argv = true
> loader.insecure__use_host_env = true
> loader.insecure__disable_aslr = true
> ```

OpenVINO PR (https://github.com/gramineproject/examples/pull/6) also has `libos.check_invalid_pointers = false`. Do you want to add this option here, for performance? Or does it break TensorFlow?
___
*[tensorflow/ResNet50/python.manifest.template, line 60 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnM2cD2K_VFhlmqdlx:-MqnM2cD2K_VFhlmqdly:bms62ve) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L60)):*
> ```
>   "file:/usr/{{ arch_libdir }}/",
>   "file:resnet50v1_5_int8_pretrained_model.pb",
>   "file:{{ entrypoint }}/",
> ```

You have a `/` at the end here, this can't be right -- the `{{ entrypoint }}` is a file, not a directory. Please remove the trailing `/`.
___
*[tensorflow/ResNet50/python.manifest.template, line 69 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnMAy11j_jl-bpWV8V:-MqnMAy11j_jl-bpWV8W:b-474iqm) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L69)):*
> ```
>   "file:/tmp/",
>   "file:/etc/",
>   "file:/proc/",
> ```

This is redundant, you're not mounting `/proc/` FS in this manifest file. Just remove this line.

**Review by Satya1493 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/7)* status: 2 of 7 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[tensorflow/README.md, line 54 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnJwAiAFHbc1oqk3qf:-MrMN9-8DnyLIwJ3hJ6U:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/README.md#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`on native baremetal (outside Gramine)` -> `natively (outside Gramine)`
</blockquote></details>

Done.
___
*[tensorflow/README.md, line 71 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnJzYF4PF8KGgGpEFW:-MrMN9v23EpEY4K6xcAD:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/README.md#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`on native baremetal (outside Gramine)` -> `natively (outside Gramine)`
</blockquote></details>

Done.
___
*[tensorflow/README.md, line 89 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnKPaS1Fi3UsRR1k-S:-MrMNpGZCpE6RKQK1CSv:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/README.md#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you copy-paste this section from https://github.com/gramineproject/examples/pull/6/files? I already reviewed the OpenVINO PR, and all comments pertaining to this `Performance considerations` section were already resolved in that OpenVINO PR.

It looks to me that these sections are 95% identical, except for `libos.check_invalid_pointers` manifest option. Don't you want to add the description of this option in your README?
</blockquote></details>

Done.
___
*[tensorflow/BERT/Makefile, line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLaCY-XKGSo7y6cGR:-MrMNVEj-pv7bR7FnyEi:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Tensorflow` -> `TensorFlow`
</blockquote></details>

Done.
___
*[tensorflow/BERT/python.manifest.template, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLADPDMV_JP-surWE:-MrMNWmH3629f8IEuUca:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/python.manifest.template#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Latest Gramine uses `loader.entrypoint` instead of `loader.preload`. Please see this commit: https://github.com/gramineproject/examples/commit/ebc051be9dad032da789a27387c36db3cbadbc95
</blockquote></details>

Done.
___
*[tensorflow/BERT/python.manifest.template, line 8 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnMV881u9MRm00RuQ5:-MrMNYsG8ZhbztHeweO7:b-k3a8c3) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/python.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OpenVINO PR (https://github.com/gramineproject/examples/pull/6) also has `libos.check_invalid_pointers = false`. Do you want to add this option here, for performance? Or does it break TensorFlow?
</blockquote></details>

It breaks TensorFlow, hence didn't add.
___
*[tensorflow/BERT/python.manifest.template, line 55 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLuk14tUzQB2zlPVw:-MrMNd7nDGey4Dmjknzz:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/BERT/python.manifest.template#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have a `/` at the end here, this can't be right -- the `{{ entrypoint }}` is a file, not a directory. Please remove the trailing `/`.
</blockquote></details>

Done.
___
*[tensorflow/ResNet50/Makefile, line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLddLAfKLjMxVRppk:-MrMNeG81MiVXGpB-XKx:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Tensorflow` -> `TensorFlow`
</blockquote></details>

Done.
___
*[tensorflow/ResNet50/python.manifest.template, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnLILV-D2DIGVWQ-_q:-MrMNfbd6hr_GRm8doCW:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Latest Gramine uses `loader.entrypoint` instead of `loader.preload`. Please see this commit: https://github.com/gramineproject/examples/commit/ebc051be9dad032da789a27387c36db3cbadbc95
</blockquote></details>

Done.
___
*[tensorflow/ResNet50/python.manifest.template, line 8 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnMda44Ursgyn4LEF1:-MrMNgyk-0hGGXXSsHCD:b-1o81q6) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OpenVINO PR (https://github.com/gramineproject/examples/pull/6) also has `libos.check_invalid_pointers = false`. Do you want to add this option here, for performance? Or does it break TensorFlow?
</blockquote></details>

It breaks TF, hence didn't add.
___
*[tensorflow/ResNet50/python.manifest.template, line 60 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnM2cD2K_VFhlmqdlx:-MrMNjkx4U45QVQKnmsn:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have a `/` at the end here, this can't be right -- the `{{ entrypoint }}` is a file, not a directory. Please remove the trailing `/`.
</blockquote></details>

Done.
___
*[tensorflow/ResNet50/python.manifest.template, line 69 at r2](https://reviewable.io/reviews/gramineproject/examples/7#-MqnMAy11j_jl-bpWV8V:-MrMNkTgBqONPbrJxjRr:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/c05a2de3c93b63af92812262e20d9b8b070a5f94/tensorflow/ResNet50/python.manifest.template#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is redundant, you're not mounting `/proc/` FS in this manifest file. Just remove this line.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/7)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/7#-MskXuhp8WoCw31fkLlE:-MskXuhp8WoCw31fkLlF:bwwrk7a) (no related file):*
Who's the author of this PR actually? It was submitted by @satya1493, but the first commit says that it's authored by @sahason.

---
___
*[tensorflow/README.md, line 1 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-MskYfZA1gsPX2YjB5_r:-MskYfZA1gsPX2YjB5_s:b7u4nni) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L1)):*
> ```Markdown
> ## Inference on TensorFlow BERT and ResNet50 models
> ```

Please add an empty line after the headings (you seem to do this only for some of the headings).
___
*[tensorflow/README.md, line 6 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msk_MLCB7ZAZLG3sO_I:-Msk_MLCB7ZAZLG3sO_J:b6v7ney) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L6)):*
> ```Markdown
> inference.
> 
> ### Bidirectional Encoder Representations from Transformers (BERT):
> ```

We usually don't put colons after headings, please remove.
___
*[tensorflow/README.md, line 7 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msk_vnNDiIsc5kWYeX3:-Msk_vnNDiIsc5kWYeX4:bp4xxw7) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L7)):*
> ```Markdown
> 
> ### Bidirectional Encoder Representations from Transformers (BERT):
> BERT is a method of pre-training language representations and then use that trained model for
> ```

`use` -> `using` (or maybe you meant something different?)
___
*[tensorflow/README.md, line 20 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-MsktAfRCHWeR9Oti_an:-MsktAfRCHWeR9Oti_ao:b-rcenvz) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L20)):*
> ```Markdown
> ## Pre-requisites
> - Upgrade pip/pip3.
> - Install TensorFlow using ``pip install intel-tensorflow-avx512==2.4.0``.
> ```

Please use single backticks instead of double.
___
*[tensorflow/README.md, line 22 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Mskbh5e3OcxBrRGrAYu:-Mskbh5e3OcxBrRGrAYv:b1zqflj) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L22)):*
> ```Markdown
> - Install TensorFlow using ``pip install intel-tensorflow-avx512==2.4.0``.
> 
> ## Build BERT or ResNet50 samples
> ```

`samples` -> `sample`
___
*[tensorflow/README.md, line 29 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-MskrzSX7EKo-mNW01B3:-MskrzSY6qAAJFeX4Dy3:b-kb8811) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L29)):*
> ```Markdown
> - To build the SGX version, do ``make PYTHONDISTPATH=path_to_python_dist_packages/ SGX=1``
> - Typically, ``path_to_python_dist_packages`` is ``/usr/local/lib/python3.6/dist-packages``, but can
> change based on python's installation directory.
> ```

These instructions were pretty unintuitive to me. Is this a list of steps to follow? Or a list of commands to pick from when you want to do a specific thing? Some entries suggest the former ("To build BERT sample, do ``cd BERT``. To build ResNet50 sample, do ``cd ResNet50``." - this point alone is just "cd", no real commands?) and some suggest the latter ("To clean the sample, do ``make clean``").
___
*[tensorflow/README.md, line 29 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-MsksVkS62f1BEvdtH-Y:-MsksVkS62f1BEvdtH-Z:b-g3j31m) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L29)):*
> ```Markdown
> - To build the SGX version, do ``make PYTHONDISTPATH=path_to_python_dist_packages/ SGX=1``
> - Typically, ``path_to_python_dist_packages`` is ``/usr/local/lib/python3.6/dist-packages``, but can
> change based on python's installation directory.
> ```

Some sentences here end with a period and some doesn't, please fix
___
*[tensorflow/README.md, line 75 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Mskv46K9Myk7GWoKnoQ:-Mskv46K9Myk7GWoKnoR:bc83scp) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L75)):*
> ```Markdown
> 
> ## Notes on optimal performance
> Above commands are for a 36 core system. Please set the following options accordingly for optimal
> ```

`36 core` -> `36-core`
___
*[tensorflow/README.md, line 112 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-MskvuR90V_UOm1ctr5Q:-MskvuRAD7wBtHZGippb:b-q58ajl) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/README.md#L112)):*
> ```Markdown
> TCMalloc and mimalloc are memory allocator libraries from Google and Microsoft that can help
> improve performance significantly based on the workloads. Only one of these
> allocators can be used.
> ```

`can be used` -> `can be used at the same time`
___
*[tensorflow/BERT/Makefile, line 23 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl0alV8pbKrfV_5XJp:-Msl-CDG9SwTk8QqL08H:b7blzjp) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/BERT/Makefile#L23)):*
> ```Makefile
> BERT_FP32_MODEL = https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_4_0/fp32_bert_squad.pb
> 
> collateral:
> ```

This should be PHONY
___
*[tensorflow/BERT/python.manifest.template, line 62 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl01TF4x_jphrleGzr:-Msl01TO0yLmEoZTSmVl:bne2gsf) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/BERT/python.manifest.template#L62)):*
> ```
> ]
> 
> sgx.allowed_files = [
> ```

If we want to allow these then we should clearly write in the readme (and maybe also here?) that this is completely insecure and what the user should do to secure this.
Same for other insecure switches.
___
*[tensorflow/BERT/python.manifest.template, line 63 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl1s5y7yiZlyOFzGMm:-Msl1s5y7yiZlyOFzGMn:b-in5k50) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/BERT/python.manifest.template#L63)):*
> ```
> 
> sgx.allowed_files = [
>   "file:/tmp/",
> ```

why not using Gramine's tmpfs?
___
*[tensorflow/ResNet50/Makefile, line 12 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl0dDi9fipS0ywHPxz:-Msl0dDi9fipS0ywHPy-:b-d4qnlp) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/ResNet50/Makefile#L12)):*
> ```Makefile
> endif
> 
> .PHONY: all collateral
> ```

Please move `.PHONY: collateral` to the line right before `collateral:`.
___
*[tensorflow/ResNet50/Makefile, line 36 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl101s6qoi6BbiWBFx:-Msl101s6qoi6BbiWBFy:b-e1uf12) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/ResNet50/Makefile#L36)):*
> ```Makefile
> 		--key $(SGX_SIGNER_KEY) \
> 		--manifest python.manifest \
> 		--output $@
> ```

please unify with the BERT example
___
*[tensorflow/ResNet50/python.manifest.template, line 67 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl1nvC3aThcDcEi9Gc:-Msl1nvD69gDsTYi7r37:b-7ropln) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/ResNet50/python.manifest.template#L67)):*
> ```
> ]
> 
> sgx.allowed_files = [
> ```

ditto
___
*[tensorflow/ResNet50/python.manifest.template, line 68 at r3](https://reviewable.io/reviews/gramineproject/examples/7#-Msl1uh75Nwrg4zTNHb3:-Msl1uh75Nwrg4zTNHb4:bu6fsaa) ([raw file](https://github.com/gramineproject/examples/blob/6b68ed89879696437f2aac7f9f697ac067cdcae8/tensorflow/ResNet50/python.manifest.template#L68)):*
> ```
> 
> sgx.allowed_files = [
>   "file:/tmp/",
> ```

ditto (tmpfs)

**Comment by dimakuv** [comment]
@Satya1493 Will you continue working on this PR?

**Comment by Satya1493** [comment]
Changes for TensorFlow are present at https://github.com/gramineproject/examples/pull/19. It incorporates all comments from this PR.

**Pull request closed without merging**
