### PR TITLE
Apply Make workaround for grouped targets to all examples

### PR DESCRIPTION
**Pull request by dimakuv**
This is similar to https://github.com/gramineproject/gramine/pull/588

I tested everything locally on my machine.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`tensorflow-lite/.gitignore` line 6 at r1](https://reviewable.io/reviews/gramineproject/examples/27#-N2jzxte0am_kwQwXkGC:-N2jzxtf3x3BiCP97Riv:b-7znp17) ([raw file](https://github.com/gramineproject/examples/blob/8ac6883f876f17869e7fb4756d48ae9232b1fee0/tensorflow-lite/.gitignore#L6)):*
> ```ignore
> /inception_v3.tflite
> /inception_v3_2018_04_27.tgz
> /label_image
> ```

FYI: Just a small fix for TensorFlow Lite, noticed when testing it.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`curl/Makefile` line 29 at r1](https://reviewable.io/reviews/gramineproject/examples/27#-N2kPtBR6iR3f8MaoPrm:-N2kajAQ9PLsRTRffM3G:b-13kvof) ([raw file](https://github.com/gramineproject/examples/blob/8ac6883f876f17869e7fb4756d48ae9232b1fee0/curl/Makefile#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should rather link to a specific commit (ditto for other places)
</blockquote></details>

Do you mean like this: `https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/CI-Examples/helloworld/Makefile`

Or like this: `https://github.com/gramineproject/gramine/commit/3f52b256e2e50badfcac9c911889f3b85fe62817`

If you mean the former, isn't it a bit too long for a comment? (I can shorten the hash in the URL, but still longish?)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`curl/Makefile` line 29 at r1](https://reviewable.io/reviews/gramineproject/examples/27#-N2kPtBR6iR3f8MaoPrm:-N2lGUCj6c3nZrlzRdcy:b-ujdldn) ([raw file](https://github.com/gramineproject/examples/blob/8ac6883f876f17869e7fb4756d48ae9232b1fee0/curl/Makefile#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you mean like this: `https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/CI-Examples/helloworld/Makefile`

Or like this: `https://github.com/gramineproject/gramine/commit/3f52b256e2e50badfcac9c911889f3b85fe62817`

If you mean the former, isn't it a bit too long for a comment? (I can shorten the hash in the URL, but still longish?)
</blockquote></details>

The former, the latter doesn't point to any specific file. I think it's ok even if it's that long, just don't wrap it.
Overall, I don't like the idea of linking to a branch instead of a commit, as it will change someday.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: 1 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`curl/Makefile` line 29 at r1](https://reviewable.io/reviews/gramineproject/examples/27#-N2kPtBR6iR3f8MaoPrm:-N2lLl48D9jSyBNCgZ53:b-7rc6q) ([raw file](https://github.com/gramineproject/examples/blob/8ac6883f876f17869e7fb4756d48ae9232b1fee0/curl/Makefile#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The former, the latter doesn't point to any specific file. I think it's ok even if it's that long, just don't wrap it.
Overall, I don't like the idea of linking to a branch instead of a commit, as it will change someday.
</blockquote></details>

Done. Kept the commit hash to 10 chars.

**Review by mkow — DISMISSED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/27#-N2lucB8BiMG-qbq1OaB:-N2lucB8BiMG-qbq1OaC:bog6qsu) (no related file):*
The PR is ready, just waiting for the release v1.2 to be done.

___

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/27)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
