### PR TITLE
Do not fetch tokens

### PR DESCRIPTION
**Pull request by anjalirai-intel**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/49#-NNkGdZV0SsNfEWUMX0I:-NNkGdZV0SsNfEWUMX0J:brp26nv) (no related file):*
Just for context, the corresponding PR in core Gramine was: https://github.com/gramineproject/gramine/pull/1093

___
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/49#-NNkG6rmCgwvrTpMUmhY):*
I would add a commit body message:
```
Starting from v1.4, Gramine automatically fetches tokens (only on
SGX platforms where it is required).
```

I can do it myself during final rebase and merge.

**Review by woju — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)* status: all files reviewed, 1 unresolved discussion (waiting on @anjalirai-intel)

**Review by mkow — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)* status: all files reviewed, 1 unresolved discussion (waiting on @anjalirai-intel)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/49#-NNkG6rmCgwvrTpMUmhY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add a commit body message:
```
Starting from v1.4, Gramine automatically fetches tokens (only on
SGX platforms where it is required).
```

I can do it myself during final rebase and merge.
</blockquote></details>

Done

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
