### PR TITLE
Remove SGX_SIGNER_KEY and update manifest files

### LINKED ISSUE #17: Convert mounts to a new format (after Gramine v1.2 release)
See https://github.com/gramineproject/gramine/pull/411 for context.

### PR DESCRIPTION
**Pull request by anjalirai-intel**
As part of latest gramine SGX_SIGNER_KEY is not required and fs.mount pattern has been updated

Fixes #17 

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/20#-MzClGtt4-pZr785p6pN:-MzClGtt4-pZr785p6pO:b-7pcw3k) (no related file):*
This needs to wait for the next release, as `examples` repo should be compatible with the most recent Gramine release (which right now doesn't support this syntax).

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/20#-MzCXSou9UQT69yqRKgc):*
One-liners should be in imperative mood. Here you use 2 different tenses/forms in one sentence and none of them is the one we use.
___
*[openjdk/java.manifest.template, line 24 at r1](https://reviewable.io/reviews/gramineproject/examples/20#-MzCiuJ01AAZeUHr3wlm:-MzCiuJ01AAZeUHr3wln:undefined) ([raw file](https://github.com/gramineproject/examples/blob/914b50081f699ffc14749827ed013901c2d0aaef/openjdk/java.manifest.template#L24)):*
> ```
> sgx.thread_num = 64
> 
> # TO-DO: Hardcoded Java path need to be updated, such path does not exist in CentOS
> ```





_Suggestion (i):_
```
TODO
```



_Suggestion (ii):_
```
needs
```



_Suggestion (iii):_
```
this
```



_Suggestion (iv):_
```
on CentOS.
```

**Comment by anjalirai-intel** [comment]
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/20#-MzCXSou9UQT69yqRKgc):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One-liners should be in imperative mood. Here you use 2 different tenses/forms in one sentence and none of them is the one we use.
</blockquote></details>

Done.

**Comment by anjalirai-intel** [comment]
___
*[openjdk/java.manifest.template, line 24 at r1](https://reviewable.io/reviews/gramineproject/examples/20#-MzCiuJ01AAZeUHr3wlm:-MzDbAoj9BnT3U0IsUJw:b-c4wdp4) ([raw file](https://github.com/gramineproject/examples/blob/914b50081f699ffc14749827ed013901c2d0aaef/openjdk/java.manifest.template#L24)):*
> ```
> sgx.thread_num = 64
> 
> # TO-DO: Hardcoded Java path need to be updated, such path does not exist in CentOS
> ```

Sentence Removed

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: 15 of 16 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/20#-MzClGtt4-pZr785p6pN:-MzoGDfOC-O5bnYNzrLy:b-c70uaf) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This needs to wait for the next release, as `examples` repo should be compatible with the most recent Gramine release (which right now doesn't support this syntax).
</blockquote></details>

+1. The PR itself is good, just needs to be postponed until we release Gramine v1.2 (which contains the new syntax as mentioned in this PR description).

---
___
*[pytorch/Makefile, line 5 at r3](https://reviewable.io/reviews/gramineproject/examples/20#-MzoH3IE8SpGPexfXtUO:-MzoH3IE8SpGPexfXtUP:b-heo695) ([raw file](https://github.com/gramineproject/examples/blob/3472b700d02768a49a8532841b02e28fee82c83f/pytorch/Makefile#L5)):*
> ```Makefile
> ARCH_LIBDIR ?= /lib/$(shell $(CC) -dumpmachine)
> 
> PILLOW_PATH ?= $(shell pip3 show pillow | grep -P 'Location' | sed 's/Location:.\(.*\)\python.*/\1/')
> ```

What's this? This is something new and seemingly irrelevant to this PR... Please explain this addition.

UPDATE: Ok, looks like it is a better way of detecting the magic `{{ env.HOME }}/.local/lib` directory. Please add a comment before this line (smth like `# PyTorch uses the Pillow backend; detect where Pillow was installed`)
___
*[pytorch/pytorch.manifest.template, line 30 at r3](https://reviewable.io/reviews/gramineproject/examples/20#-MzoHyzL2pA4_CYeIoDq:-MzoHyzL2pA4_CYeIoDr:b-a1kno0) ([raw file](https://github.com/gramineproject/examples/blob/3472b700d02768a49a8532841b02e28fee82c83f/pytorch/pytorch.manifest.template#L30)):*
> ```
> # fs.mount.torch.type = "chroot"
> # fs.mount.torch.path = "{{ env.HOME }}/.cache/torch"
> # fs.mount.torch.uri = "file:{{ env.HOME }}/.cache/torch"
> ```

Please add this as a separate (commented out) line in `fs.mounts` array, and keep an explanatory comment.

(If this is not possible in TOML syntax, then please change this comment to ask to add the line to `fs.mounts`)

**Comment by anjalirai-intel** [comment]
*[pytorch/Makefile, line 5 at r3](https://reviewable.io/reviews/gramineproject/examples/20#-MzoH3IE8SpGPexfXtUO:-MzsFPh0AAlK6VxD45YQ:bengt9d) ([raw file](https://github.com/gramineproject/examples/blob/3472b700d02768a49a8532841b02e28fee82c83f/pytorch/Makefile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's this? This is something new and seemingly irrelevant to this PR... Please explain this addition.

UPDATE: Ok, looks like it is a better way of detecting the magic `{{ env.HOME }}/.local/lib` directory. Please add a comment before this line (smth like `# PyTorch uses the Pillow backend; detect where Pillow was installed`)
</blockquote></details>

Okay. I will add the comment.

**Comment by anjalirai-intel** [comment]
*[pytorch/pytorch.manifest.template, line 30 at r3](https://reviewable.io/reviews/gramineproject/examples/20#-MzoHyzL2pA4_CYeIoDq:-MzsFyKu7QPkxA2EfEf3:b32w1t) ([raw file](https://github.com/gramineproject/examples/blob/3472b700d02768a49a8532841b02e28fee82c83f/pytorch/pytorch.manifest.template#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add this as a separate (commented out) line in `fs.mounts` array, and keep an explanatory comment.

(If this is not possible in TOML syntax, then please change this comment to ask to add the line to `fs.mounts`)
</blockquote></details>

Ok

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[-- commits, line 6 at r4](https://reviewable.io/reviews/gramineproject/examples/20#-N--ipLj-aldosgb77p4):*
What's this?

**Comment by anjalirai-intel** [comment]
*[-- commits, line 6 at r4](https://reviewable.io/reviews/gramineproject/examples/20#-N--ipLj-aldosgb77p4):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

I was testing tensorflow example into another branch. By mistake commit message got updated. Removed it

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel and @mkow)

___
*[-- commits, line 6 at r4](https://reviewable.io/reviews/gramineproject/examples/20#-N--ipLj-aldosgb77p4):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

I was testing tensorflow example into another branch. By mistake commit message got updated. Removed it
</blockquote></details>

I still see this message. But we can remove this line during final rebase.

**Comment by anjalirai-intel** [comment]
*[-- commits, line 6 at r4](https://reviewable.io/reviews/gramineproject/examples/20#-N--ipLj-aldosgb77p4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still see this message. But we can remove this line during final rebase.
</blockquote></details>

Gone. Done

**Review by mkow — COMMENTED** [review]
> Reviewed 7 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

**Comment by anjalirai-intel** [comment]
*[a discussion](https://reviewable.io/reviews/gramineproject/examples/20#-MzClGtt4-pZr785p6pN:-N-XlRVj62nEc9999Rs2:b32wtd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. The PR itself is good, just needs to be postponed until we release Gramine v1.2 (which contains the new syntax as mentioned in this PR description).
</blockquote></details>

ok

---

**Review by dimakuv — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

**Comment by anjalirai-intel** [comment]
*[openvino/benchmark_app.manifest.template, line 27 at r7](https://reviewable.io/reviews/gramineproject/examples/20#-N0EpstZ8qedqK92vS0q:-N0EpstZ8qedqK92vS0r:bab2s4) ([raw file](https://github.com/gramineproject/examples/blob/cbeb944a7184be4038192dee717769eb15c9b21e/openvino/benchmark_app.manifest.template#L27)):*
> ```
> sgx.trusted_files = [
>   "file:benchmark_app",
>   "file:{{ gramine.libos }}",
> ```

This change is required for Openvino benchmark for SGX.

Without it, it fails with error "error: PAL failed at ../Pal/src/db_main.c:pal_main:543 (exitcode = 6, reason=Unable to load loader.entrypoint)"

**Review by mkow — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel and @dimakuv)

___
*[`openvino/benchmark_app.manifest.template` line 27 at r7](https://reviewable.io/reviews/gramineproject/examples/20#-N0EpstZ8qedqK92vS0q:-N0YJRn48IId2rDGZY5P:b-5vn0l0) ([raw file](https://github.com/gramineproject/examples/blob/cbeb944a7184be4038192dee717769eb15c9b21e/openvino/benchmark_app.manifest.template#L27)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

This change is required for Openvino benchmark for SGX.

Without it, it fails with error "error: PAL failed at ../Pal/src/db_main.c:pal_main:543 (exitcode = 6, reason=Unable to load loader.entrypoint)"
</blockquote></details>

Why did you put this remark as a blocking comment?

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 4 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/20)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel and @dimakuv)

**Pull request merged**
