### PR TITLE
Add MongoDB example

### PR DESCRIPTION
**Pull request by sahason**
Add MongoDB example.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcLj-044ta-onybF9Pf:-NcLj-044ta-onybF9Pg:b-uk994s) (no related file):*
@jinengandhi-intel @anjalirai-intel Will we be able to add MongoDB example to our CI? So that we can test it periodically (especially before each new release).

___
___
*[`mongodb/Makefile` line 23 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLjcXT2lCZOlnYNJnV:-NcLjcXT2lCZOlnYNJnW:b-spmses) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/Makefile#L23)):*
> ```Makefile
> 
> # Make on Ubuntu <= 20.04 doesn't support "Rules with Grouped Targets" (`&:`),
> # see the helloworld example for details on this workaround.
> ```

Please remove this second line, as we are in the Examples repo and there is no Helloworld.
___
*[`mongodb/mongod.manifest.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLjzk-5-d-2lV2a7hz:-NcLjzk-5-d-2lV2a7i-:b-didce2) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/mongod.manifest.template#L8)):*
> ```
> loader.argv = ["mongod", "--nounixsocket"]
> 
> loader.env.LD_LIBRARY_PATH = "/lib:/usr{{ arch_libdir }}"
> ```

Please add `/` after `usr`. I know it doesn't matter much (because `{{ arch_libdir }}` already contains it), but it will help readability and uniformity with the rest of this file.
___
*[`mongodb/README.md` line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl9L_2DYbbs0gHH87:-NcLl9L_2DYbbs0gHH88:bdjgm3p) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L8)):*
> ```Markdown
> # Generating the manifest
> 
> ## Installing prerequisite
> ```

`prerequisite` -> `prerequisites`
___
*[`mongodb/README.md` line 23 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLks9BDPHkhrpSbvMr:-NcLks9BDPHkhrpSbvMs:b-xep2s3) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L23)):*
> ```Markdown
>        ```
>        curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
>            sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
> ```

@woju Could you check if this command line is the correct way?
___
*[`mongodb/README.md` line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl0-BEHma26gu2Q9a:-NcLl0-BEHma26gu2Q9b:b-xep2s3) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L30)):*
> ```Markdown
>    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] \
>        https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | \
>        sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
> ```

@woju Could you check if this command line is the correct way?
___
*[`mongodb/README.md` line 70 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl1zsBGrWkdcwBBKW:-NcLl1zt6ceO85HLa3S2:bwfliiy) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L70)):*
> ```Markdown
> Run the below commands from a new terminal:
> 
> - `mongosh scripts/insert.js` # inserts new documents into a collection
> ```

Please replace `#` with e.g. `-`, otherwise it renders funny: https://github.com/sahason/examples/tree/sahason/mongodb-example/mongodb#testing-client-connection
___
*[`mongodb/README.md` line 71 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl7LN2tVuFpOQlbKk:-NcLl7LN2tVuFpOQlbKl:b-7ropln) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L71)):*
> ```Markdown
> 
> - `mongosh scripts/insert.js` # inserts new documents into a collection
> - `mongosh scripts/fetch.js` # fetches all documents, and prints their content
> ```

ditto

**Review by jinengandhi-intel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcLj-044ta-onybF9Pf:-NcLlgwm7QIYrpauQi8d:b-6i38po) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@jinengandhi-intel @anjalirai-intel Will we be able to add MongoDB example to our CI? So that we can test it periodically (especially before each new release).
</blockquote></details>

Sure once the PR gets merged, we will add to local CI running every night across all distros. As a general practice, we do this for anything new that gets merged to examples repo.

___

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcLj-044ta-onybF9Pf:-NcLqJJHEpuPuI9Tor_t:btf9f8g) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

Sure once the PR gets merged, we will add to local CI running every night across all distros. As a general practice, we do this for anything new that gets merged to examples repo.
</blockquote></details>

Thanks for the info, resolving this comment.

___

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: 4 of 7 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[`mongodb/Makefile` line 23 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLjcXT2lCZOlnYNJnV:-NcPzOGp5GPuHylcdx2_:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/Makefile#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this second line, as we are in the Examples repo and there is no Helloworld.
</blockquote></details>

Done.
___
*[`mongodb/mongod.manifest.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLjzk-5-d-2lV2a7hz:-NcPzZqo2xCmdk2_gXdA:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/mongod.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `/` after `usr`. I know it doesn't matter much (because `{{ arch_libdir }}` already contains it), but it will help readability and uniformity with the rest of this file.
</blockquote></details>

Done.
___
*[`mongodb/README.md` line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl9L_2DYbbs0gHH87:-NcQ-B8u96mSB39WmPku:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`prerequisite` -> `prerequisites`
</blockquote></details>

Done.
___
*[`mongodb/README.md` line 70 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl1zsBGrWkdcwBBKW:-NcQ-DKG62yi36ALvVJN:barlkro) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `#` with e.g. `-`, otherwise it renders funny: https://github.com/sahason/examples/tree/sahason/mongodb-example/mongodb#testing-client-connection
</blockquote></details>

replaced with `-`
___
*[`mongodb/README.md` line 71 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl7LN2tVuFpOQlbKk:-NcQ-HoH1TcvJCJ9iA1K:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`mongodb/Makefile` line 22 at r2](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ1f5i-1WAVumB5nbv:-NcQ1f5i-1WAVumB5nbw:bhvwrbd) ([raw file](https://github.com/gramineproject/examples/blob/66ed9e89b16c1e28491e4ce14dd9c31a73717c31/mongodb/Makefile#L22)):*
> ```Makefile
> 		$< $@
> 
> # Make on Ubuntu <= 20.04 doesn't support "Rules with Grouped Targets" (`&:`),
> ```

Please remove the comma at the end of this line

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`mongodb/Makefile` line 22 at r2](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ1f5i-1WAVumB5nbv:-NcQ3ubA92Ad2Q32EcIy:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/66ed9e89b16c1e28491e4ce14dd9c31a73717c31/mongodb/Makefile#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the comma at the end of this line
</blockquote></details>

Done.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: 6 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`mongodb/Makefile` line 22 at r2](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ1f5i-1WAVumB5nbv:-NcQ5n5n0fGzfedJx7Yt:bt2vr1b) ([raw file](https://github.com/gramineproject/examples/blob/66ed9e89b16c1e28491e4ce14dd9c31a73717c31/mongodb/Makefile#L22)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fixed.

**Review by dimakuv — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ6FMdBKwQpVXoMutQ:-NcQ6FMdBKwQpVXoMutR:b-f5jhmn) (no related file):*
The PR looks fine to me.

___

**Review by woju — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[`mongodb/README.md` line 23 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLks9BDPHkhrpSbvMr:-NcRl0jB5o5ld4TNg6rH:bopgtzt) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Could you check if this command line is the correct way?
</blockquote></details>

Looks like one of correct variants to me. You can also `sudo curl -o /usr/share/keyrings/mongodb-server-6.0.asc` and adjust `signed-by=` below (you don't need to dearmor). @sahason where did you get this snippet from? If it was some official HOWTO, then we definitely keep it this way. If you figured this out yourself, then we could simplify (but I'm not insisting).
___
*[`mongodb/README.md` line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl0-BEHma26gu2Q9a:-NcRlnLi5cvXIl_ZlAiR:b-dmip2s) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Could you check if this command line is the correct way?
</blockquote></details>

It's correct, but I woudn't break the line inside quotes (there are cases where this would break at copy-pasting, though if you copy-paste as-is, then it should work) and it's not my style to leave spaces just inside of `[]`. Again, this might work as-is, and if it's stolen from official mongodb docs, then I say we leave it like that.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`mongodb/README.md` line 23 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLks9BDPHkhrpSbvMr:-NcRr4iM75tkQcgv1snO:btoavjn) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L23)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Looks like one of correct variants to me. You can also `sudo curl -o /usr/share/keyrings/mongodb-server-6.0.asc` and adjust `signed-by=` below (you don't need to dearmor). @sahason where did you get this snippet from? If it was some official HOWTO, then we definitely keep it this way. If you figured this out yourself, then we could simplify (but I'm not insisting).
</blockquote></details>

@woju Yes, it is from offical HOWTO. Link -https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/
___
*[`mongodb/README.md` line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl0-BEHma26gu2Q9a:-NcRriYJ-GKiyPrmqoGM:b5p8v6u) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L30)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's correct, but I woudn't break the line inside quotes (there are cases where this would break at copy-pasting, though if you copy-paste as-is, then it should work) and it's not my style to leave spaces just inside of `[]`. Again, this might work as-is, and if it's stolen from official mongodb docs, then I say we leave it like that.
</blockquote></details>

@Woju This is from official website https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/. The spaces inside of `[]` is present in this link. But the line inside quotes is broken into two lines to keep the limit of character within 100 per line. Copy pasting this from README works without any issue but if suggested I will move this to same line.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ6FMdBKwQpVXoMutQ:-NcRtM1UCtYWiOoV8kZb:b9h6xol) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks fine to me.
</blockquote></details>

@dimakuv There is a newer version (7.0) available now for MongoDB. Do you suggest updating this PR to move to 7.0?

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`mongodb/README.md` line 23 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLks9BDPHkhrpSbvMr:-NcS-f-L0Qj83IDNqzVu:b-7dt4gl) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L23)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

@woju Yes, it is from offical HOWTO. Link -https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/
</blockquote></details>

That's what I suspected. Thanks for confirmation and for the link.
___
*[`mongodb/README.md` line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl0-BEHma26gu2Q9a:-NcS-w7w54tAwf44jH1a:b-xd9ide) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L30)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

@Woju This is from official website https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/. The spaces inside of `[]` is present in this link. But the line inside quotes is broken into two lines to keep the limit of character within 100 per line. Copy pasting this from README works without any issue but if suggested I will move this to same line.
</blockquote></details>

Yes, it works until someone pastes this into something that doesn't respect newlines and/or messes with spaces, like email or markdown outside <code>```</code> blocks. I suggest to break the line only at `|`, where it's at least clear what's going on and you can manually fix after snafu. Disregard 100-char limits, it does apply for things that you actually can break (I think here it makes more harm than good). Otherwise LGTM, spaces inside `[]` should remain.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`mongodb/README.md` line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/75#-NcLl0-BEHma26gu2Q9a:-NcVuX2w7aJ5rckdatjJ:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e6bda8241366af005fbafc1e431c53b1d18557ae/mongodb/README.md#L30)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, it works until someone pastes this into something that doesn't respect newlines and/or messes with spaces, like email or markdown outside <code>```</code> blocks. I suggest to break the line only at `|`, where it's at least clear what's going on and you can manually fix after snafu. Disregard 100-char limits, it does apply for things that you actually can break (I think here it makes more harm than good). Otherwise LGTM, spaces inside `[]` should remain.
</blockquote></details>

Done

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ6FMdBKwQpVXoMutQ:-NcY3KWKBaFqBWeSJ0yU:b-s7v4zj) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

@dimakuv There is a newer version (7.0) available now for MongoDB. Do you suggest updating this PR to move to 7.0?
</blockquote></details>

@sahason If the newer version of MongoDB just works on Gramine, then yes please, update to this latest version.

___

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: 7 of 8 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/75#-NcQ6FMdBKwQpVXoMutQ:-Nd94e--2PgBGpz_TzlR:b-y8p0sk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason If the newer version of MongoDB just works on Gramine, then yes please, update to this latest version.
</blockquote></details>

Updated with latest version of MongoDB (7.0).

___

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`mongodb/README.md` line 10 at r6](https://reviewable.io/reviews/gramineproject/examples/75#-NdXdy92BzZWvO0rlaus:-NdXdy92BzZWvO0rlaut:b-8u4wy7) ([raw file](https://github.com/gramineproject/examples/blob/51ac93dd6a610b2633016e1880e6efee1057b679/mongodb/README.md#L10)):*
> ```Markdown
> ## Installing prerequisites
> 
> Please run the following commands to install MongoDB 7.0 Community Edition on Ubuntu 20.04:
> ```

Why adding a new example for an old Ubuntu? I'd move this to 22.04 to not have to update it in a moment.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`mongodb/README.md` line 10 at r6](https://reviewable.io/reviews/gramineproject/examples/75#-NdXdy92BzZWvO0rlaus:-NdYxQct8bdcudWmUt1j:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/51ac93dd6a610b2633016e1880e6efee1057b679/mongodb/README.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why adding a new example for an old Ubuntu? I'd move this to 22.04 to not have to update it in a moment.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/75)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
