### PR TITLE
Update sgx.max_threads in manifest templates

### PR DESCRIPTION
**Pull request by anjalirai-intel**
This change is made wrt dynamic edmm pr

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)* status: 0 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/84#-NjrZ4Y86Yr0b-G3v-La:-NjrZ4Y86Yr0b-G3v-Lb:blinyrg) (no related file):*
Blocking until we merge https://github.com/gramineproject/gramine/pull/1451

___

**Review by mkow — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/84#-NjrYoKd-ymkJvt1qj3p):*
Please fix the one-liner, now it doesn't really say anything (what does "update" mean in terms of max_threads? it sounds very confusing)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @anjalirai-intel and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/84#-NjrYoKd-ymkJvt1qj3p):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix the one-liner, now it doesn't really say anything (what does "update" mean in terms of max_threads? it sounds very confusing)
</blockquote></details>

+1. I can do during final rebase.

**Review by kailun-qin — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @anjalirai-intel and @mkow)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/84#-NjrZ4Y86Yr0b-G3v-La:-NlhP5eS04imXoK4vI2a:bpn8m3y) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking until we merge https://github.com/gramineproject/gramine/pull/1451
</blockquote></details>

This was merged.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/84#-NjrYoKd-ymkJvt1qj3p):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. I can do during final rebase.
</blockquote></details>

Done

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/84)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
