### PR TITLE
Add README and gitignore

### PR DESCRIPTION
**Pull request by dimakuv**
Contents are based on the core Gramine repo.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[.gitignore, line 20 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjEzINm9ld-6oPABFav:-MjEzINm9ld-6oPABFaw:b354p86) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/.gitignore#L20)):*
> ```ignore
> *.so.*
> 
> # gnu global
> ```

what's this?
___
*[.gitignore, line 26 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjEzJpQB47smoVffFGp:-MjEzJpQB47smoVffFGq:b-7ropln) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/.gitignore#L26)):*
> ```ignore
> GRTAGS
> 
> # tags/etags
> ```

ditto
___
*[.gitignore, line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjEzKSw6iX_MtWqQOam:-MjEzKSw6iX_MtWqQOan:bqgv6ye) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/.gitignore#L30)):*
> ```ignore
> TAGS
> 
> # cscope
> ```

doesn't seem useful for this repo
___
*[README.rst, line 63 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjFcDoY9Gjmk4OZ1nyb:-MjFcDoY9Gjmk4OZ1nyc:b-saadfo) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/README.rst#L63)):*
> ```
> In addition, we ask you to provide sufficient comments
> ```

Could we drop this? We don't want that copy-pasted comments anymore.
___
*[README.rst, line 73 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjFcbqcATXUulJFX5Em:-MjFcbqcATXUulJFX5En:b-7ropln) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/README.rst#L73)):*
> ```reStructuredText
>   way is to create a manifest template that contains variables to be replaced by
>   runtime options in ``Makefile``. See other subdirectories for examples of the
>   manifest templates. We also ask you to provide sufficient comments in all the
> ```

ditto

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[.gitignore, line 20 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjEzINm9ld-6oPABFav:-MjSthDG8iGWN960KbwF:b-wnfmk9) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/.gitignore#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

Done. Removed.
___
*[.gitignore, line 26 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjEzJpQB47smoVffFGp:-MjSti3XA7HysIEjP7Nt:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/.gitignore#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[.gitignore, line 30 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjEzKSw6iX_MtWqQOam:-MjStiKi-gcauqdrTXYH:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/.gitignore#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

doesn't seem useful for this repo
</blockquote></details>

Done.
___
*[README.rst, line 63 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjFcDoY9Gjmk4OZ1nyb:-MjStvDq-Zdbg-UN-RPj:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/README.rst#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> In addition, we ask you to provide sufficient comments
> ```

Could we drop this? We don't want that copy-pasted comments anymore.
</blockquote></details>

Done.
___
*[README.rst, line 73 at r1](https://reviewable.io/reviews/gramineproject/examples/3#-MjFcbqcATXUulJFX5Em:-MjSu44b7cMLCY17VYxM:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/028930de5af19bdd42779c17a4312b79b242a61f/README.rst#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[README.rst, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/3#-MjWaJ6e2-RlzUvihDXp:-MjWaJ6f0sNDO937kkEl:bzgg586) ([raw file](https://github.com/gramineproject/examples/blob/618513cd4ccca56c3e17ac32279325970460423b/README.rst#L2)):*
> ```reStructuredText
> ***************************************
> Example applications enabled in Gramine
> ```

Could we use some other term for this? It always sounds to me like we've done something special to the applications (e.g. recompile them).
Update: we seem to be using it in quite a few places, so not blocking.

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[README.rst, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/3#-MjWaJ6e2-RlzUvihDXp:-MjWeAaA0I6HZtKQ0rfk:b-fxce0v) ([raw file](https://github.com/gramineproject/examples/blob/618513cd4ccca56c3e17ac32279325970460423b/README.rst#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we use some other term for this? It always sounds to me like we've done something special to the applications (e.g. recompile them).
Update: we seem to be using it in quite a few places, so not blocking.
</blockquote></details>

+1, I also don't like this term. Maybe "[...] configured to run in Gramine" or "[...] configurations for Gramine"?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: 1 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[README.rst, line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/3#-MjWaJ6e2-RlzUvihDXp:-MjXy_uWAqYNygNyx5vz:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/618513cd4ccca56c3e17ac32279325970460423b/README.rst#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1, I also don't like this term. Maybe "[...] configured to run in Gramine" or "[...] configurations for Gramine"?
</blockquote></details>

Done.

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
