### PR TITLE
Remove benchmark-http.sh

### PR DESCRIPTION
**Pull request by anjalirai-intel**
It is not being used by any of the examples present in Gramine Repo.

Signed-off-by: Anjali Rai <anjali.rai@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/34#-N5ZaL6p7UQhA6M_HfKj):*
Needs an empty line before this sentence.

`Gramine Repo` -> `this repo`.

I will fix it during final rebase.

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @anjalirai-intel)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)* status: all files reviewed, 1 unresolved discussion (waiting on @anjalirai-intel)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/34#-N5ZaL6p7UQhA6M_HfKj):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Needs an empty line before this sentence.

`Gramine Repo` -> `this repo`.

I will fix it during final rebase.
</blockquote></details>

Done

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
