### PR TITLE
Update PyTorch manifest template

### PR DESCRIPTION
**Pull request by dimakuv**
~~OLD TEXT: PyTorch README describes local (non-root) installation. However, the manifest template worked only with system-wide (root) installation. This was because Gramine couldn't find where `torchvision` was installed.~~

This PR has several fixes:

- removed `loader.insecure__use_host_env`,
- removed deprecated `loader.pal_internal_mem_size`,
- removed stale commented-out manifest options,
- use `python.get_sys_path()` to list Python system paths,
- add `torchvision` local path: this fixes non-root installation.

Local installation on my random Ubuntu 22.04 machine is like this:
```
~/examples/pytorch$ pip3 show torchvision pillow
Name: torchvision
Version: 0.15.1
...
Location: /home/sdp/.local/lib/python3.10/site-packages
---
Name: Pillow
Version: 9.0.1
...
Location: /usr/lib/python3/dist-packages
```

The system-wide installation on the same machine is like this:
```

~/examples/pytorch$ sudo pip3 show torchvision pillow
Name: torchvision
Version: 0.15.1
...
Location: /usr/local/lib/python3.10/dist-packages
---
Name: Pillow
Version: 9.0.1
...
Location: /usr/lib/python3/dist-packages
```

For context, see also:
- https://github.com/gramineproject/examples/issues/31
- https://github.com/gramineproject/examples/pull/39

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsKbLS2HxYn5CpCiXV:-NTsKbLS2HxYn5CpCiXW:b3fttae) (no related file):*
@anjalirai-intel @jkr0103 @jinengandhi-intel Could you verify this PR on your machines? I tested it with clean Ubuntu 22.04 and Ubuntu 20.04, following the README instructions (https://github.com/gramineproject/examples/blob/master/pytorch/README.md) strictly. It worked for me. But I'd like to double check on more systems.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsLA0o4s02Z1R59HI-:-NTsLA0p6CKS5g3uJ2Na:b-xagzxk) (no related file):*
@mkow @woju Could any of you review this PR? I think this one is pretty trivial.

___

**Comment by anjalirai-intel** [comment]
*[`pytorch/pytorch.manifest.template` line 45 at r1](https://reviewable.io/reviews/gramineproject/examples/63#-NTsLkt83973d2MRWbHA:-NTsLkt83973d2MRWbHB:bqzvi5u) ([raw file](https://github.com/gramineproject/examples/blob/5aad0c337b5fcef7090f44b731e97efd3dc3d3a1/pytorch/pytorch.manifest.template#L45)):*
> ```
>   "file:/usr/{{ arch_libdir }}/",
>   "file:{{ python.stdlib }}/",
>   "file:{{ python.distlib }}/",
> ```

A query here,  Can we also remove python.distlib and replace it with python.get_sys_path(entrypoint) % becauase some distros does not have distlib

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: 0 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[`pytorch/pytorch.manifest.template` line 45 at r1](https://reviewable.io/reviews/gramineproject/examples/63#-NTsLkt83973d2MRWbHA:-NTsXBdY1sa_zUiqMM-z:b-yi5qv0) ([raw file](https://github.com/gramineproject/examples/blob/5aad0c337b5fcef7090f44b731e97efd3dc3d3a1/pytorch/pytorch.manifest.template#L45)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

A query here,  Can we also remove python.distlib and replace it with python.get_sys_path(entrypoint) % becauase some distros does not have distlib
</blockquote></details>

Done. Modified a lot of stuff in this example, as it was in a pretty bad shape.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: 0 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsKbLS2HxYn5CpCiXV:-NTsYZx9ELp09XPJY9F4:b-i81g9x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@anjalirai-intel @jkr0103 @jinengandhi-intel Could you verify this PR on your machines? I tested it with clean Ubuntu 22.04 and Ubuntu 20.04, following the README instructions (https://github.com/gramineproject/examples/blob/master/pytorch/README.md) strictly. It worked for me. But I'd like to double check on more systems.
</blockquote></details>

FYI: I verified the new revision of this PR on my Ubuntu 20.04 and 22.04, works fine for me.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsLA0o4s02Z1R59HI-:-NTsYdX-9dFuLaEgb_oo:b-g7m543) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow @woju Could any of you review this PR? I think this one is pretty trivial.
</blockquote></details>

Ok, not that trivial anymore... The example was in a bad shape, decided to modify it significantly.

___
___
*[`pytorch/pytorch.manifest.template` line 9 at r2](https://reviewable.io/reviews/gramineproject/examples/63#-NTsYjY-5g6hAXY0C_PS:-NTsYjY-5g6hAXY0C_PT:b-szvbok) ([raw file](https://github.com/gramineproject/examples/blob/7a646413eb460302610990ad8905649697b12d8e/pytorch/pytorch.manifest.template#L9)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"
> loader.env.HOME = "{{ env.HOME }}"
> ```

FYI: This is now needed because I removed `loader.insecure__use_host_env` manifest option. And Python needs to find locally installed packages, and for this Python needs to know the `HOME` envvar.

**Comment by anjalirai-intel** [comment]
*[`pytorch/pytorch.manifest.template` line 25 at r2](https://reviewable.io/reviews/gramineproject/examples/63#-NTvzPEMEsDiGhZqpazz:-NTvzPEMEsDiGhZqpb--:b-4mjte5) ([raw file](https://github.com/gramineproject/examples/blob/7a646413eb460302610990ad8905649697b12d8e/pytorch/pytorch.manifest.template#L25)):*
> ```
>   { path = "{{ path }}", uri = "file:{{ path }}" },
> {% endfor %}
>   { path = "{{ pillow_path }}", uri = "file:{{ pillow_path }}" },
> ```

pillow_path and torchvision_path will be present as python.get_sys_path. These are duplicate entries

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: 0 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsKbLS2HxYn5CpCiXV:-NTwfUMC65_rvQPQPt8l:b-riqb1c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I verified the new revision of this PR on my Ubuntu 20.04 and 22.04, works fine for me.
</blockquote></details>

Verified again. @anjalirai-intel Could you also verify the new version of this PR again?

___
___
*[`pytorch/pytorch.manifest.template` line 25 at r2](https://reviewable.io/reviews/gramineproject/examples/63#-NTvzPEMEsDiGhZqpazz:-NTwf_4o6d0v1kkFSvmJ:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/7a646413eb460302610990ad8905649697b12d8e/pytorch/pytorch.manifest.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wow, @anjalirai-intel is right. I experimentally verified this duplicatoin. Here is the result on my Ubuntu systems:

- The paths from `python.get_sys_path()`:
```
path = "/home/dimakuv/gramineproject/gramine/built-debug/lib/python3.8/site-packages"
path = "/home/dimakuv/gramineproject/examples/pytorch"
path = "/usr/lib/python3.8"
path = "/usr/lib/python3.8/lib-dynload"
path = "/home/dimakuv/.local/lib/python3.8/site-packages"
path = "/usr/local/lib/python3.8/dist-packages"
path = "/usr/lib/python3/dist-packages"
```

- The paths of `{{ pillow_path }}` and `{{ torchvision_path }}`:
```
path = "/usr/lib/python3/dist-packages/"
path = "/home/dimakuv/.local/lib/python3.8/site-packages/"
```

As you can see, they are indeed duplicated. So I will remove `pillow_path` and `torchvision_path` now completely. Let's see how it will work.
</blockquote></details>

Done.

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel and @jkr0103)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel, @jinengandhi-intel, and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsKbLS2HxYn5CpCiXV:-NUa-xxv18m7S5JOxmz2:b2rzuw9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Verified again. @anjalirai-intel Could you also verify the new version of this PR again?
</blockquote></details>

@anjalirai-intel Ping. Could you verify?

___

**Comment by anjalirai-intel** [comment]
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@anjalirai-intel Ping. Could you verify?
</blockquote></details>

Sure

**Comment by anjalirai-intel** [comment]
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Verified on Ubuntu 22.04, it passed

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsKbLS2HxYn5CpCiXV:-NUa8WOWEvuSEfL5hZnT:be7z3jt) (no related file):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Verified on Ubuntu 22.04, it passed
</blockquote></details>

LGTM. Thanks @anjalirai-intel.

@mkow This verification is done. Can we proceed with merging this PR?

___

**Review by mkow — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/63)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/63#-NTsKbLS2HxYn5CpCiXV:-NUdXogb7HCKh2brnaXt:b-gjfq3l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

LGTM. Thanks @anjalirai-intel.

@mkow This verification is done. Can we proceed with merging this PR?
</blockquote></details>

Sure, please go ahead and rebase it.

___

**Pull request merged**
