### PR TITLE
Remove java-atk-wrapper from openjdk example

### PR DESCRIPTION
**Pull request by anjalirai-intel**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood (waiting on @anjalirai-intel)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00yg5n0GenCOS9HF-2):*




_Suggestion:_
```
Remove java-atk-wrapper from openjdk example
```
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00ymGW7STmO055ApwV):*
Please explain why are you removing it.

**Comment by anjalirai-intel** [comment]
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00ymGW7STmO055ApwV):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please explain why are you removing it.
</blockquote></details>

I was running this workload inside CentOS and this file is not present, so I updated the manifest file for removing this file and workload ran fine.

I tried this experiment on Ubuntu 18.04 and Ubuntu 20.04 and workload runs fine, no error

Ubuntu 18.04
rasp@rasp-WHITLEY:~/Anjali/examples/openjdk$ gramine-sgx java MultiThreadMain
Parsing TOML manifest file, this may take some time...

Final Count is: 10000
rasp@rasp-WHITLEY:/Anjali/examples/openjdk$ cat java.manifest | grep java-atk-wrapper
rasp@rasp-WHITLEY:/Anjali/examples/openjdk$ cat /etc/os-release | grep VERSION_ID
VERSION_ID="18.04"

Ubuntu 20.04
intel@intel-WHITLEY:~/anjali/examples/openjdk$ gramine-sgx java MultiThreadMain
Parsing TOML manifest file, this may take some time...

Final Count is: 10000
intel@intel-WHITLEY:/anjali/examples/openjdk$ cat java.manifest | grep java-atk-wrapper
intel@intel-WHITLEY:/anjali/examples/openjdk$ cat /etc/os-release | grep VERSION_ID
VERSION_ID="20.04"

**Comment by anjalirai-intel** [comment]
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00ymGW7STmO055ApwV):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

I was running this workload inside CentOS and this file is not present, so I updated the manifest file for removing this file and workload ran fine.

I tried this experiment on Ubuntu 18.04 and Ubuntu 20.04 and workload runs fine, no error

Ubuntu 18.04
rasp@rasp-WHITLEY:~/Anjali/examples/openjdk$ gramine-sgx java MultiThreadMain
Parsing TOML manifest file, this may take some time...

Final Count is: 10000
rasp@rasp-WHITLEY:/Anjali/examples/openjdk$ cat java.manifest | grep java-atk-wrapper
rasp@rasp-WHITLEY:/Anjali/examples/openjdk$ cat /etc/os-release | grep VERSION_ID
VERSION_ID="18.04"

Ubuntu 20.04
intel@intel-WHITLEY:~/anjali/examples/openjdk$ gramine-sgx java MultiThreadMain
Parsing TOML manifest file, this may take some time...

Final Count is: 10000
intel@intel-WHITLEY:/anjali/examples/openjdk$ cat java.manifest | grep java-atk-wrapper
intel@intel-WHITLEY:/anjali/examples/openjdk$ cat /etc/os-release | grep VERSION_ID
VERSION_ID="20.04"
</blockquote></details>

So, Dmitrii asked to create a PR to remove this file from example

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel and @mkow)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00ymGW7STmO055ApwV):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

So, Dmitrii asked to create a PR to remove this file from example
</blockquote></details>

I will add the following commit message, to explain the change in Git:
```
This file doesn't exist in CentOS, and is irrelevant for Ubuntu 18.04/20.04.
```

**Comment by anjalirai-intel** [comment]
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00yg5n0GenCOS9HF-2):*
Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/23#-N00ymGW7STmO055ApwV):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

_I_ know why are you removing this, but the commit didn't explain it.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/23)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
