### PR TITLE
Add a note on release-for-release matching with core Gramine

### PR DESCRIPTION
**Pull request by dimakuv**
Additionally, update the notes on OS distros and Gramine versions for GCC and Scikit-learn.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)

### CODE REVIEW

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`README.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/examples/101#-NxCZ9SUCUahjSqMg1fZ:-NxCZ9SUCUahjSqMg1f_:bd6d1jr) ([raw file](https://github.com/gramineproject/examples/blob/d8bfdb772fc74140e2ca7762e95176ee23489002/README.rst#L31)):*
> ```reStructuredText
> template, we recommend to remove the comments from your copies as they only add
> noise (see e.g. `Memcached
> <https://github.com/gramineproject/gramine/tree/master/CI-Examples/memcached>`__
> ```

I think this should be a relative URL? Otherwise it will always teleport to `master`.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`README.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/examples/101#-NxCZ9SUCUahjSqMg1fZ:-NxCbr7C8ZJFxN1UI3qv:b-v3fy4r) ([raw file](https://github.com/gramineproject/examples/blob/d8bfdb772fc74140e2ca7762e95176ee23489002/README.rst#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this should be a relative URL? Otherwise it will always teleport to `master`.
</blockquote></details>

Relative to what? We link from the `examples` repo to the `gramine` repo. So if you meant that, I don't think this is allowed in GitHub's RST?

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`README.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/examples/101#-NxCZ9SUCUahjSqMg1fZ:-NxDOFJV7m3IsaAqypz4:bk4re86) ([raw file](https://github.com/gramineproject/examples/blob/d8bfdb772fc74140e2ca7762e95176ee23489002/README.rst#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Relative to what? We link from the `examples` repo to the `gramine` repo. So if you meant that, I don't think this is allowed in GitHub's RST?
</blockquote></details>

Ah, I missed that it changes the repo.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/101#-NxDOiIg1xjcJknRPBDt:-NxDOiIg1xjcJknRPBDu:b-smw2b1) (no related file):*
Blocking comment to first discuss it with all stakeholders (during Tuesday and Wednesday meetings)

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)* status: all files reviewed, 1 unresolved discussion

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/101)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

**Pull request closed without merging**
